/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   social-icons.html
 */

/// <reference path="../iron-icon/iron-icon.d.ts" />

