/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   demo/index.html
 */

/// <reference path="../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../paper-styles/demo-pages.d.ts" />
/// <reference path="../../paper-styles/color.d.ts" />
/// <reference path="../../iron-meta/iron-meta.d.ts" />
/// <reference path="../iron-icons.d.ts" />
/// <reference path="../av-icons.d.ts" />
/// <reference path="../communication-icons.d.ts" />
/// <reference path="../device-icons.d.ts" />
/// <reference path="../editor-icons.d.ts" />
/// <reference path="../hardware-icons.d.ts" />
/// <reference path="../image-icons.d.ts" />
/// <reference path="../maps-icons.d.ts" />
/// <reference path="../notification-icons.d.ts" />
/// <reference path="../social-icons.d.ts" />
/// <reference path="../places-icons.d.ts" />

